#!/usr/bin/env bash
# Creates the 5 Ethioaiventure scheduled jobs (opt-in).
# Usage: ./cron/setup-jobs.sh   (run with the profile alias active)
# Jobs are NOT auto-created by install — run this to enable them.

echo "==> Creating daily-intelligence"
hermes cron create "0 8 * * *" "Act as Ethioaiventure, the Ethiopian & African AI venture intelligence agent. Perform today's LIGHTWEIGHT daily intelligence scan. Research significant developments in (1) Ethiopia: startups, AI companies, technology, policy, research, investment, infrastructure, local-language AI; (2) Africa: AI startups, funding, launches, research, policy, infrastructure, acquisitions, partnerships; (3) Global: ONLY items with meaningful relevance to African markets or AI economics. RESEARCH BUDGET: this is a lightweight daily scan - limit yourself to at most 10 web search/fetch tool calls total; prioritize Ethiopia first, then Africa; skip deep global research. Apply the quality filter: Relevance + Materiality + Credibility + Novelty + African/Ethiopian impact. Report only high-signal items - this is NOT a generic news dump. Check your previous run's output (continuity) and the dedup ledger at ${HERMES_HOME}/research/intelligence/.state/ledger.json; never re-report stories unless materially updated; append new item fingerprints (source URL + title + date) to the ledger. For each major item include: what happened, why it matters, evidence, confidence, potential opportunity, recommended action. Classify evidence (FACT/REPORTED/INFERENCE/ESTIMATE/ASSUMPTION/UNVERIFIED). If nothing meaningful happened, note: No material developments detected. - never fabricate activity. ARCHIVING RULE: Use the write_file tool to save the FULL report to ${HERMES_HOME}/research/intelligence/daily/YYYY-MM-DD.md (current date from your system context), following the template: Critical Developments, Ethiopia, Africa, Global, Opportunity Signals, Risk Signals, Market/Funding Signals, Technology Signals, What Matters, Recommended Actions, Sources (source, publication date, discovery date, source type, confidence, verification status). Do NOT dump the full report in your final response. End with a SHORT final response: 2-4 sentence summary of the top items plus the archive path." --name daily-intelligence --skill ecosystem-research --skill research-reporting --deliver telegram,local 

echo "==> Creating monthly-market"
hermes cron create "0 9 1 * *" "Act as Ethioaiventure. Produce the monthly market review. Analyze the past month across: Ethiopia, East Africa, Africa, and global AI developments relevant to Africa. Track: market changes, startup formation, funding, AI adoption, infrastructure, regulation, competition, technology, pricing, customer behavior. Compare with previous months' reports (check ${HERMES_HOME}/research/intelligence/monthly/). Classify trends: Accelerating, Stable, Declining, Emerging, Disappearing. Dedupe against previous output (continuity) and the ledger at ${HERMES_HOME}/research/intelligence/.state/ledger.json. Classify evidence for major claims. ARCHIVING RULE: Use write_file to save the FULL report to ${HERMES_HOME}/research/intelligence/monthly/YYYY-MM-market.md (current month from your system context). Do NOT dump the full report in your final response. End with a SHORT final response: 2-4 sentence summary plus the archive path." --name monthly-market --skill market-research --skill competitive-intelligence --deliver telegram,local 

echo "==> Creating monthly-strategy"
hermes cron create "0 9 2 * *" "Act as Ethioaiventure. Produce the monthly strategic review. Synthesize the month's intelligence into venture-building decisions. Include: Executive Summary, Major Changes, Strongest Opportunity Signals, Weakening Opportunities, New Risks, Technology Changes, Competitive Changes, Ethiopia Outlook, Africa Outlook, Global Signals, What We Were Wrong About (MANDATORY - explicitly state incorrect assumptions from previous months; check ${HERMES_HOME}/research/intelligence/ for prior reports), Assumptions That Changed, Highest-Conviction Opportunities, Opportunities Requiring Validation, Recommended Experiments, Strategic Priorities For Next Month, Open Questions, Sources. Red-team the strongest opportunities: what evidence would change the conclusion? Dedupe via continuity and the ledger at ${HERMES_HOME}/research/intelligence/.state/ledger.json. ARCHIVING RULE: Use write_file to save the FULL report to ${HERMES_HOME}/research/intelligence/monthly/YYYY-MM-strategy.md (current month). Do NOT dump the full report in your final response. End with a SHORT final response: 2-4 sentence summary plus the archive path." --name monthly-strategy --skill intelligence-dashboard --skill red-team --skill research-reporting --deliver telegram,local 

echo "==> Creating weekly-ecosystem"
hermes cron create "0 9 * * 1" "Act as Ethioaiventure. Produce the weekly ecosystem intelligence report covering the previous seven days. Research: Ethiopia (companies, research, investment, policy, infrastructure), East Africa, Africa, and Global AI items relevant to African opportunities. Include: emerging trends, new companies/products, funding signals, research breakthroughs, policy signals, opportunity signals, risk signals, competitive changes. Apply the quality filter (Relevance + Materiality + Credibility + Novelty + African/Ethiopian impact) and dedupe against your previous run's output (continuity) and the ledger at ${HERMES_HOME}/research/intelligence/.state/ledger.json; append new fingerprints to the ledger. Classify evidence for major claims. If nothing material happened in a section, say so. ARCHIVING RULE: Use write_file to save the FULL report to ${HERMES_HOME}/research/intelligence/weekly/YYYY-Www.md (current ISO week from your system context), template: Executive Summary, Ethiopia (Companies/Research/Investment/Policy/Infrastructure), East Africa, Africa, Global AI, Emerging Trends, New Companies/Products, Funding Signals, Research Breakthroughs, Policy Signals, Opportunity Signals, Risk Signals, Competitive Changes, What Changed This Week, What Matters Most, Recommended Actions, Sources. Do NOT dump the full report in your final response. End with a SHORT final response: 2-4 sentence summary plus the archive path." --name weekly-ecosystem --skill ethiopia-intelligence --skill african-market-analysis --skill research-reporting --deliver telegram,local 

echo "==> Creating weekly-opportunity"
hermes cron create "0 9 * * 4" "Act as Ethioaiventure. Perform the weekly opportunity scan. Identify emerging opportunities from: emerging problems, newly available technologies, new infrastructure, regulatory changes, market gaps, new competitors, falling AI costs, new datasets, new APIs, new African startups, underserved sectors. For each ranked opportunity include: Why Now, Customer, Problem, AI Advantage, Competition, Market, Defensibility, Evidence (class + confidence), Opportunity Score /100 (13 dimensions: problem severity, market size, growth, AI leverage, willingness to pay, competition, technical feasibility, data availability, distribution, defensibility, capital efficiency, Ethiopia/Africa advantage, expansion potential), Validation Experiment (hypothesis, success metric, failure threshold), Verdict (BUILD/TEST/WATCH/AVOID). Do NOT generate opportunities to fill a quota - quality over quantity; if nothing rises above threshold, say so. Dedupe against previous output (continuity) and the ledger at ${HERMES_HOME}/research/intelligence/.state/ledger.json. ARCHIVING RULE: Use write_file to save the FULL report to ${HERMES_HOME}/research/intelligence/weekly/YYYY-Www-opportunities.md (current ISO week). Do NOT dump the full report in your final response. End with a SHORT final response: the ranked list summary plus the archive path." --name weekly-opportunity --skill opportunity-discovery --skill opportunity-scoring --deliver telegram,local 
